### ISSUE TITLE
如果能增加对焦就完美了

### ISSUE THREAD

**Issue by RondaHo** [hawk0620/ZPCamera#1]
首先感谢作者开源这么精美的项目。该项目非常适合集成到有拍摄需求的APP中。
另外问一下，该版本相比appstore版本少了几个滤镜效果，这几个效果可以开源么

**Comment by hawk0620** [comment]
谢谢你的支持，对焦的功能以后有空我再加上。对于滤镜我也很抱歉，具体原因在博客里说明了。最后还是谢谢你的肯定；）

**Comment by hawk0620** [comment]
I've already add focus function.
