### ISSUE TITLE
程序一运行就崩，求解

### ISSUE THREAD

**Issue by miliPolo** [hawk0620/ZPCamera#13]
Main Thread Checker: UI API called on a background thread: -[UIView bounds]
PID: 1054, TID: 571404, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0

**Comment by hawk0620** [comment]
崩溃信息说的是子线程调用了 UI 方法，可以告诉下我是什么机器什么系统出现的吗

**Comment by miliPolo** [comment]
iPhone 6s iOS 11

**Comment by miliPolo** [comment]
大佬能帮忙看下是什么问题吗？

**Comment by hawk0620** [comment]
iOS 11 beta6 控制台会有 GPUImage 抛出的上述信息，但是不会引起闪退，应该还是 beta 系统导致。
