### ISSUE TITLE
关于滤镜文件的问题

### ISSUE THREAD

**Issue by RunsCode** [hawk0620/ZPCamera#4]
你好！ 最近我做类似的app,有幸看您这么优秀的开源库！其中我有些疑问：你这个滤镜文件 .acv格式，是怎么制作的？或者说什么软件配置好生成的？谢谢

**Comment by hawk0620** [comment]
你好，acv格式文件是通过 photoshop 生成的，具体你可以搜索看看是怎么通过 photoshop 调出来的，lut格式也是 photoshop 调出来的。滤镜更多还得是由设计师去调试，也谢谢你的认可与支持；）

**Comment by RunsCode** [comment]
好的 ， 非常感谢！
