### ISSUE TITLE
闪光灯

### ISSUE THREAD

**Issue by mzying2013** [hawk0620/ZPCamera#8]
请问为什么闪光灯设置后，没有打开闪光灯呢？Demo的闪光灯按钮也是灰色的。
1. iPhone6  iOS 10.0.2
2. iPhone5s iOS 10.2.1

**Comment by mzying2013** [comment]
NSLog(@"是否支持闪光灯:%@",self.videoCamera.hasFlash?@"YES":@"NO");
返回NO

**Comment by hawk0620** [comment]
抱歉，应该是我添加聚焦功能不小心留下的一个 bug，我会尽快去修复，谢谢你的指出；）

**Comment by mzying2013** [comment]
谢谢你的回复。
